### ISSUE TITLE
App exits in the middle of downloading of Russia

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#246]
Thailand is downloaded successfully.

**Comment by paandahl** [comment]
I was looking through the crash logs, and there's nothing related to downloading. It's strange because if the app exits, it should be there. If the connection fails, you should just get a message "Connection failure" in the app.

 Can you delete your app, re-install, and try to download again? If it fails again, it will be easier to see from the logs (because you were doing many other things the day you tested it first).

**Comment by paandahl** [comment]
You can wait with testing again, I think I have discovered a problem. Need to investigate further.

**Comment by paandahl** [comment]
I think I fixed it. There was a problem that the file was first downloaded into memory, and then written to disk. But the file was too big for memory (the map of Russia is huge), so now it loads a bit, writes it, load a bit, writes it, and so on.

**Comment by NayaMakarova** [comment]
It works :) But downloading is veeeeery slow, and as you said we can't do anything about it.

**Comment by paandahl** [comment]
It is a bit specific to Russia - the map is 20 times bigger than most other countries, so it will take 20 times longer to download.

What we can do, is allow the users to download separate cities in the future.
